name: Self-Update

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Run Workflow
        run: mvn compile exec:java -Dexec.mainClass="paizo.crawler.Workflow"
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          if [[ `git status --porcelain` ]]
          then
            git commit -m "Automatical Update"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        
